# Generated by Django 5.2.7 on 2025-11-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_user_email_verified_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='proof_of_payment',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
    ]
